### ISSUE TITLE
Cursor is sent to the bottom of the buffer after performing deletion

### ISSUE THREAD

**Issue by musjj** [chomosuke/term-edit.nvim#45]
I'm using MSYS2 on Windows
![2023-01-21_20-52-39](https://user-images.githubusercontent.com/72612857/213870061-58b1691b-20d4-4bf5-9296-88459fadadf2.gif)

**Comment by chomosuke** [comment]
#46 Should've fixed this, I'd be grateful if you can update to the latest on master and test if this is still an issue :)
