### ISSUE TITLE
Multiline command navigation

### ISSUE THREAD

**Issue by egr95** [chomosuke/term-edit.nvim#48]
Thank you for this awesome plugin! This really helps my workflow as I am a heavy user of the nvim terminal (I love navigating my terminals with my vim bindings and I had always wanted to have corresponding edit commands available).

I was wondering if it would be easy to add support for multiline commands? For example, say I am writing the following for loop in bash:
```
for number in 1 2 3 4 5
do
    echo "Number is: $number"
done
```
Now suppose I start at the bottom line, exit to normal mode, navigate up one line, and then enter insert mode again. The cursor will go to the beginning of the bottom line rather than staying put on the penultimate line.

Such examples in bash may be relatively rare, but where I think this would be really useful is for interactive work such as when using ipython with [vim-slime](https://github.com/jpalardy/vim-slime). In this case, one may want to navigate and/or edit a multiline command with the same ease that your plugin already affords for the single-line case. Even if a multiline visual mode is too difficult to implement, just the ability to navigate up and down would already be a great asset to the nvim terminal.

Thanks again!

**Comment by chomosuke** [comment]
Hmmm, that is bizarre, I thought I fixed this with #27 and I was not able to reproduce the issue. What shell are you using?

One thing that could help is increasing `feedkeys_delay` to a higher value, perhaps 100 or even 1000 and check if the problem still presist.

Another thing to check is whether you've set `prompt_end` correctly.

And thank you for the kind words! It's a pleasure to know that my plugin is improving people's workflow :).

**Comment by egr95** [comment]
Somehow I get the issue regardless of whether I use bash (with `prompt_end = '%$ '`) or zsh (in this case I use `prompt_end = '> '` which is what my custom prompt looks like). Increasing `feedkeys_delay` did not help either.

How would the plugin handle an ipython prompt such as:
```
~$ ipython
[ins] In [1]: for i in range(5):
         ...:     print(i)
```
Would this require setting `prompt_end = ']: '`? I am completely unable to navigate between the two lines regardless of whether I applied this setting or any of the other `prompt_end` options. Single-line navigation always works fine regardless of the config.

Does the ipython case work for you?

**Comment by chomosuke** [comment]
For me the ipython case didn't work but I see what you mean now.

For the bash case, I wasn't able to reproduce your issue because I copied your loop instead of typing it out as I've never written bash script in bash straight away. 

After typing it out, I was able to reproduce the issue, however I'm not sure how this plugin can fix it because:
- This plugin move the cursor in terminal move by simulating left and right arrow keys. 
- I'm not sure what keys does this plugin have to simulate to move the cursor in terminal move up one line, up and down arrow certainly doesn't work.

For the ipython case, I see that you are able to move the cursor up and down with the up and down arrow key. I think this is a fair enough feature to implement. Right now I am thinking of two ways to implement this:
- An boolean option `up_down_arrow` where if you set it to true, it'll attempt to navigate with up and down arrow after failing to navigate with left and right arrow.
- A callback (callbacks) that user can pass in that determine what keys they want to simulate based on the cursor position difference.

Feels like the second option will be a lot more general purpose and might work pretty well. I am busy recently though so I might not get to it in a month or so. In the mean time, you can try to tackle this with a PR if you want.

**Comment by egr95** [comment]
Got it, thanks! 

For multiline navigation, I could get a hacky version of `navigate_with` which adds vertical movements, simply passing `<Up>` or `<Down>` as many times as `target.line - current.line`. However, this sidesteps your existing multiline logic in `navigate_line`, so I must be breaking other non-ipython multiline cases. The thing is, in the ipython prompt, the left arrow will not navigate from the beginning of a line to the end of the previous; one needs to use up arrows. For deletion purposes, the backspace key still crosses linebreaks, however counting the number of backspaces correctly might require some additional logic.

It's my first time writing lua code so will probably have to defer to your input.

**Comment by chomosuke** [comment]
I think a cool idea is to have a config option called `use_up_down_arrow: function() -> boolean` (open to better name) where the function is called before the plugin does anything else to determine if the plugin will use up and down arrow for navigation. In this way you can always use up down arrow in ipython and never use it in bash. It might work with other environment too.

**Comment by chomosuke** [comment]
@egr95 I've done it.

I pushed it to https://github.com/chomosuke/term-edit.nvim/tree/up-down-arrow-navigation, I'd appreciate it if you test it out and see if it works.

Here are my config that made it work for ipython:
```
require 'term-edit'.setup {
  prompt_end = ' %$ ',
  use_up_down_arrows = function()
    local line = vim.fn.getline(vim.fn.line '.') -- get content for line under cursor
    if line:find(']:', 1, true) or line:find('...:', 1, true) then
      return true
    else
      return false
    end
  end,
}
```

Will write the documentation and open PR soon, probably tomorrow.

**Comment by egr95** [comment]
This didn't work for me. When I exit normal mode, and navigate up or down by 1 line, inserting takes me to the right place. However, if I navigate by 2 lines, inserting only carries me up or down by 1 line. It also doesn't let me combine vertical and horizontal motion, so if I hit escape, navigate up and right and then insert, it's as if I had only passed one up arrow.

Note also that deletion seems to have broken? For example, if I want to delete the word I am on, I have to press `Esc` `dwdw` instead of just `Esc` `dw`.

I have tested this behavior on bash and zsh, with and without tmux, and on mate-terminal as well as putty.

**Comment by chomosuke** [comment]
Hmm that is really weird, because for me all of the cases you mentioned above work. As the screen recording shows, it works for inserting two lines above, vertical and horizontal motion, and `dw`

https://github.com/chomosuke/term-edit.nvim/assets/38484873/85d5d1e6-2308-407d-92f7-78cb36828f19

Maybe try to create a minimum reproducible config with more detail about your environment? Are you testing with ipython?

**Comment by chomosuke** [comment]
Also maybe set debug to true and send me the debug output? The debug output can be obtained by `:message`.

**Comment by egr95** [comment]
Here is my debug output following the same motions from your video, up to when you delete `print`:
```
0.147407 key i in mode n
0.147497 enter_insert: target:  { col = 1, line = 1 }
0.150497 move_line:  { col = 28, line = 2 }
0.150511 move_by:  -28
0.153738 move_line:  { col = 28, line = 2 }
0.153801 move_col:  { col = 28, line = 2 }
0.175319 key i in mode n
0.17551 enter_insert: target:  { col = 19, line = 7 }
0.177266 move_line:  { col = 27, line = 9 }
0.177282 using up down arrow to move
0.18049 move_line:  { col = 27, line = 9 }
0.18063 move_col:  { col = 27, line = 9 }
0.190661 key i in mode n
0.190884 enter_insert: target:  { col = 23, line = 9 }
0.192836 move_line:  { col = 27, line = 8 }
0.192851 using up down arrow to move
0.196109 move_line:  { col = 27, line = 8 }
0.196187 move_col:  { col = 27, line = 8 }
0.208522 key i in mode n
0.208629 enter_insert: target:  { col = 23, line = 7 }
0.210339 move_line:  { col = 27, line = 9 }
0.21037 using up down arrow to move
0.213549 move_line:  { col = 27, line = 9 }
0.213569 move_col:  { col = 27, line = 9 }
0.220744 key d in mode n
0.221141 delete_range: start: { col = 19, line = 8 } end: { col = 24, line = 8 }
0.221187 enter_insert: target:  { col = 25, line = 8 }
0.222747 move_line:  { col = 27, line = 8 }
0.222767 move_col:  { col = 27, line = 8 }
0.222775 using up down arrow to move
0.222783 move_by:  -2
0.226007 move_line:  { col = 27, line = 8 }
0.226023 move_col:  { col = 27, line = 8 }
0.226031 delete_by: -8
```
After pressing `dw` on `print`, I am left with the following text:
```
[ins] In [1]: for i in range(5):
         ...:   i)
         ...:     print(i)
```

As for a minimal reproducible `init.vim`, it's literally just the plugin:
```

"#### Plugins list. Managed by vim-plug.
call plug#begin()
Plug 'https://github.com/chomosuke/term-edit.nvim'
call plug#end()

" -- Calling require 'term-edit'.setup(opts) is mandatory
lua <<EOF
require 'term-edit'.setup {
  prompt_end = ' %$ ',
  use_up_down_arrows = function()
    local line = vim.fn.getline(vim.fn.line '.') -- get content for line under cursor
    if line:find(']:', 1, true) or line:find('...:', 1, true) then
      return true
    else
      return false
    end
  end,
  mapping = {
      n = { s = false }
  },
  debug = true,
}
EOF
```

With regard to my environment, I am running ipython 8.14.0 which is the same as you. I wonder if there's a difference in how our terminals interpret the keypresses sent. Are you sending anything other than the arrow keys and backspaces? I'm also confused as to what might be causing these inconsistencies.

**Comment by egr95** [comment]
Another thing I checked is whether this behavior could be dependent on whether the input mode for the shell / ipython prompt is itself set to vi mode. I originally had the vi mode switched on, but switching it off didn't seem to make a difference.

**Comment by chomosuke** [comment]
So after reading your debug output, I am convinced that your `feedkeys_delay` is too low.

The reason I came to this conclusion is that, looking at your debug output, it seems that after the <Up> key is dispatched, the cursor position did not change.

This could explain the behavior of only being able to move up one line and no horizontal movement after that, as once the plugin observe that the cursor did not move after <Up>, it assume the target is unreachable and it stops.

However the `feedkeys_delay` is clearly working well for your horizontal movement though, so I'm guessing ipython takes a long time to process <Up> and <Down> for some reason. This is pretty weird because it doesn't do that on my machine and I have my `feedkeys_delay` set to 2 which is even lower than the default. What operating system are you on?

Btw, you mentioned you got a hacky version of `navigate_with` before, did that work well for you? If so mind sharing the code?

**Comment by egr95** [comment]
The `feedkeys_delay` seems unlikely as I have had it set to 1000 for most of the past couple of days.

My implementation for the navigation part was dead simple but it works: just pass the right number of keys and remove all the extra logic. However, for delete operations it seems like the more complex logic is needed. Here is the code diff. Again, note that this only works for navigating the cursor but not for the other operations.

```diff
diff --git a/lua/term-edit/insert.lua b/lua/term-edit/insert.lua
index 433e564..71e46f3 100644
--- a/lua/term-edit/insert.lua
+++ b/lua/term-edit/insert.lua
@@ -16,12 +16,25 @@ function M.move_keys(len)
   end
 end
 
+---move down by len
+---@param len integer negative mean move left
+function M.move_rows(len)
+  utils.debug_print('move_by: ', len)
+  if len > 0 then
+    return string.rep('<Down>', len)
+  elseif len < 0 then
+    return string.rep('<Up>', -len)
+  else
+    return ''
+  end
+end
+
 ---Enter insert mode and place cursor at target
 ---@param callback? function
 function M.insert_at(target, callback)
   utils.debug_print('enter_insert: target: ', utils.inspect(target))
   async.vim_cmd('startinsert', function()
-    navigate.navigate_with(target, M.move_keys, callback)
+    navigate.navigate_with(target, M.move_keys, M.move_rows, callback)
   end)
 end
 
diff --git a/lua/term-edit/navigate.lua b/lua/term-edit/navigate.lua
index 71983f0..7323f72 100644
--- a/lua/term-edit/navigate.lua
+++ b/lua/term-edit/navigate.lua
@@ -7,7 +7,7 @@ local M = {}
 ---@param target Coord
 ---@param move_keys function
 ---@param callback? function this function will be called after target is reached
-function M.navigate_with(target, move_keys, callback)
+function M.navigate_with(target, move_keys, move_rows, callback)
   local function navigate_col()
     local current = coord.get_coord '.'
     utils.debug_print('move_col: ', utils.inspect(current))
@@ -33,25 +33,31 @@ function M.navigate_with(target, move_keys, callback)
       navigate_col()
       return
     end
-    local col_end = vim.fn.col '$'
-    local move_len
-    if current.line < target.line then
-      -- move to end + one right to move to line below
-      move_len = col_end - current.col
-      if move_len == 0 then
-        -- encountered <CR>, need to move one more to get to the next line
-        move_len = 1
-      end
-    else
-      -- move to start + one left to move to line above
-      move_len = -current.col
-    end
-    old = current
-    async.feedkeys(move_keys(move_len), function()
-      navigate_line(old)
-    end, {
+    async.feedkeys(move_rows(target.line - current.line), callback, {
+      moves = true,
+    })
+    async.feedkeys(move_keys(target.col - current.col), callback, {
       moves = true,
     })
   end
```

**Comment by chomosuke** [comment]
Although I still don't know why doesn't my previous logic work, I do think yours is probably cleaner and faster for all arrow navigation so I did something that is similar (should be essentially the same) to your logic when `use_up_down_arrows` return true.

Deletion was still a bit hit and miss for me but increasing `feedkeys_delay` to 20 seems to have ~~fixed that for me~~ nope, it didn't fix it.

Multiline delete still doesn't work and significant work is required to make it work.

I've pushed to the same branch and I'd appreciate it if you test it out and see if it works :).

**Comment by chomosuke** [comment]
Update: if you increase feedkeys_delay to 10,000 then everything will work as expected (except multi-line delete). I suspect even my previous implementation will work just fine.

**Comment by egr95** [comment]
Setting a large `feedkeys_delay` works! The main downside I see is that this setting seems to cause occasional glitches when speeding through several normal mode actions at high pace (for instance jumping across many lines using easymotion and immediately deleting some selection). However this seems to happen very rarely.

I actually realized I hadn't properly set the large `feedkeys_delay` on your [previous implementation](https://github.com/chomosuke/term-edit.nvim/commit/8acfcd0bde07c63570e59923b72b4ce8e569993a), which in fact also worked (albeit it was substantially more glitchy than your latest code).

Thanks again for all the work here! I'm already using this for my day-to-day work so will report back with any other issues.

While I'm at it, a couple of minor things I noticed (happy to open separate issues if needed):
- In normal mode, `x` works fine but my `X` doesn't?
- Long commands can cause issues, not in the terminal but in ipython. For example if the cursor is at the end of the following command, then if your window width is <120 characters, the `print` will sit a line above the cursor. If we navigate to `print` in normal mode and then hit `i`, we end up sending an up arrow, which in this case is wrong because there was no actual line break. The result is to discard our command and recover the previous command. This may not be easy to fix but it's minor.
```
print("A very very very very very very very very very very very very very very very very very very very very very very very very long line")
```

**Comment by chomosuke** [comment]
That is good to hear! You probably don't have to set a large `feedkeys_delay` just for ipython if you don't delete things regularly.

I did not know `X` existed hence why it's not implemented. I've already done it actually... while writing this comment, just had to map it to `dh`. Will open an PR soon after some procrastination.

With the very long line case, I guess you would try to fall back to the regular style of navigation if up down arrow doesn't work? But I don't think the case comes up often enough to warrant an implementation tbh. Regardless I'm more than happy to accept an PR from you if you'd like.

And thank you for all your work as well for raising the issue and testing my implementation!
