### ISSUE TITLE
It's a good idea to add a `clear=true` for the augroup

### ISSUE THREAD

**Issue by nyngwang** [chomosuke/term-edit.nvim#49]
As title. Adding the `clear=true` can prevent some tricky errors caused by the accumulating of autocmds.

https://github.com/chomosuke/term-edit.nvim/blob/3c2385d5d058720928a96e77c405466478fb711a/lua/term-edit/init.lua#L22

**Comment by IndianBoy42** [comment]
`clear=true` is the default already
