### ISSUE TITLE
How to deactivate the <C-p> binding?

### ISSUE THREAD

**Issue by cherryramatisdev** [chomosuke/term-edit.nvim#51]
I managed to disable the <C-i>, but I can't disable the <c-p>

my sample config using lazy.nvim:

```lua
  {
    "chomosuke/term-edit.nvim",
    lazy = false,
    opts = {
      prompt_end = '%🍒 ',
      mapping = {
        n = {
            ['<C-i>'] = false,
            ['<C-P>'] = false,
            ['<C-p>'] = false
        },
        x = {
            ['<C-P>'] = false,
            ['<C-p>'] = false
        }
    },
    },
    version = "1.*",
  },

```

**Comment by chomosuke** [comment]
> I managed to disable the , but I can't disable the
> 
> my sample config using lazy.nvim:
> 
> ```lua
>   {
>     "chomosuke/term-edit.nvim",
>     lazy = false,
>     opts = {
>       prompt_end = '%🍒 ',
>       mapping = {
>         n = {
>             ['<C-i>'] = false,
>             ['<C-P>'] = false,
>             ['<C-p>'] = false
>         },
>         x = {
>             ['<C-P>'] = false,
>             ['<C-p>'] = false
>         }
>     },
>     },
>     version = "1.*",
>   },
> ```

**Comment by chomosuke** [comment]
Should be fixed in #52, I'd appreciate it if you can test it out to confirm that it is indeed fixed :).

**Comment by cherryramatisdev** [comment]
@chomosuke Sorry for the delay on answering, it's working perfectly thanks a lot !

**Comment by chomosuke** [comment]
No worries, thanks for testing it!
