### ISSUE TITLE
Scrolling up during `git add -p` in normal mode causes many `^[[D` to dump into terminal mode

### ISSUE THREAD

**Issue by ColinKennedy** [chomosuke/term-edit.nvim#56]
## Summary
If you make a git repository with unstage changes and type `git add -p` in a terminal with term-edit.nvim included, when you scroll up using `k` in `normal` mode and switch back to `terminal` mode, term-edit.nvim appears to dump `^[[D` for every time you press `k`.

## Demonstration
https://github.com/chomosuke/term-edit.nvim/assets/10103049/0d23703e-450f-4569-ac05-a5a082549628

## Reproduction
1. Create a git repository with unstaged changes. e.g.

```sh
cd /tmp
mkdir fake_git_repository_001
cd fake_git_repository_001
git init
echo "First line" > README.md
git add README.md
git commit -m "Initial commit"
echo -e "\n\n\n\nmore lines\nFirst line" > README.md
```

2. Save the reproduction file to disk and call it `reproduction.lua`
<details>
<summary>Click to expand reproduction file</summary>

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
	"git",
	"clone",
	"--filter=blob:none",
	"--single-branch",
	"https://github.com/folke/lazy.nvim.git",
	lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
    -- Allow terminal buffers to be edited
    {
	"chomosuke/term-edit.nvim",
	config = function()
	    -- Calling require 'term-edit'.setup(opts) is mandatory
	    require 'term-edit'.setup {
		-- Mandatory option:
		-- Set this to a lua pattern that would match the end of your prompt.
		-- Or a table of multiple lua patterns where at least one would match the
		-- end of your prompt at any given time.
		-- For most bash/zsh user this is '%$ '.
		-- For most powershell/fish user this is '> '.
		-- For most windows cmd user this is '>'.
		prompt_end = '%$ ',
		-- How to write lua patterns: https://www.lua.org/pil/20.2.html
	    }
	end,
    },
}

require("lazy").setup(plugins, {
    root = root .. "/plugins",
})
```
</details>

3. Load neovim and create a terminal buffer

```sh
nvim -u reproduction.lua
```

4. Call `git add -p`
5. Exit `terminal` mode  (`<C-\><C-n>`)
6. Scroll up by holding the `k` key
7. Go back to terminal mode (`i` key)

**Comment by chomosuke** [comment]
Hello there, currently there's no possible way that I know of that can fix this problem. The issue is that:
- In your particular case, it's not actually possible for the cursor to move to the location of your cursor in normal mode. But there's no way for term-edit to know that, so it has to try anyways.
- The only way for it to try is to feedkeys "\<Left\>" which will cause ^[[D to be displayed.

The work around is to use \<C-i\> instead, which will enter terminal mode without trying to move the cursor.

Hope that helps.

**Comment by ColinKennedy** [comment]
> The work around is to use instead, which will enter terminal mode without trying to move the cursor.

Sorry, what do we use? I think something got cut off in your response

**Comment by chomosuke** [comment]
Oh sorry, edited!
