### ISSUE TITLE
Termedit appears to cause issues with keymaps in terminal-normal mode

### ISSUE THREAD

**Issue by samjwill** [chomosuke/term-edit.nvim#57]
Hi! Thanks for the wonderful plugin.

I have noticed some odd keymap behavior that I felt it would be useful to point out. I use `s` as a search/jump-to keymap with [flash.nvim](https://github.com/folke/flash.nvim). I know [leap.nvim](https://github.com/ggandor/leap.nvim) also has a similar philosophy of remapping `s`. However, when the plugin is installed, mapping this doesn't appear to work in terminal buffers in terminal-normal mode as expected.

### Steps to reproduce:

1. Ensure term-edit.nvim is installed. I did it with [lazy.nvim](https://github.com/folke/lazy.nvim).
2. Execute the following two commands:
`:lua vim.keymap.set('n', '<F5>', function() print('This works!') end, {})`
`:lua vim.keymap.set('n', 's', function() print('This does not work!') end, {})`
3. Open a terminal buffer with `:ter`. Ensure that the terminal is in terminal-normal mode, and not terminal-insert mode with `Ctrl-\` + `Ctrl-n`.
4. Press `<F5>` on the keyboard. Observe that "This works!" is printed at the bottom of the screen.
5. Press `s` on the keyboard. Observe that "This does not work!" is not printed at the bottom of the screen, and instead, insert mode has been entered.

### Expected behavior:

* When pressing `s` on the keyboard, "This does not work!" should be printed. Terminal-insert mode should not be entered.

Repeating the above steps, but launching Neovim without plugins via `nvim -u NONE` results in the expected behavior occurring.

Please let me know if any more information would be helpful.

**Comment by chomosuke** [comment]
Hello there,

Sorry for the late response.

term-edit works by calling `vim.keymap` to map various keys such as `i`, `a` and `s` to lua functions that does the heavy lifting of simulation what a normal nvim buffer should behave.

When you open a terminal buffer, term-edit will call `vim.keymap` with `s` as `lhs` and hence overwritting your earlier `vim.keymap` call.

To prevent this, you can do
```
require 'term-edit'.setup {
    mapping = {
        n = {
            s = false,
        },
    },
}
```

More explanation about the `mapping` option can be found with `:h term-edit.mapping`.

Hope that helps :)
