### ISSUE TITLE
Termedit plugin is not enabled when open terminal buffer with "nvim -c ':term'"

### ISSUE THREAD

**Issue by blandong** [chomosuke/term-edit.nvim#58]
If I open nvim first, then type ':term' to enter the terminal buffer, the term-edit plugin works correctly. 

However, if I open the terminal buffer with the "nvim -c ':term'" command, the term-edit plugin is not enabled because I cannot edit the command.

Please help take a look.

**Comment by chomosuke** [comment]
Hello there,

I'm dying of assignments rn. Will respond and hopefully fix next month.

**Comment by blandong** [comment]
Sure, thank you, take your time.

**Comment by chomosuke** [comment]
Hi there,

Sorry for the delay, the issue should be fixed in #62, I'd appreciate it if you test it out :).
