### ISSUE TITLE
Use the `TermOpen` event in lazy.nvim

### ISSUE THREAD

**Issue by kamack38** [chomosuke/term-edit.nvim#64]
I think that the installation instructions should be changed for `lazy.nvim`, because there is an event (`TermOpen`) that runs when a terminal is opened. The installation instruction should look as following:

```lua
{
    'chomosuke/term-edit.nvim',
    event = { 'TermOpen' },
    version = '1.*',
}
```

**Comment by chomosuke** [comment]
Thank you for your suggestion.
